name: Upload

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact
  upload-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2
      - name: Upload first
        uses: actions/upload-artifact@v4
        with:
          name: artifact1
          path: artifact1
      - name: Upload second
        uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: artifact2
  upload-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact_duplicate
          echo $GITHUB_SHA > artifact/sha
      - name: Upload first
        uses: actions/upload-artifact@v4
        with:
          name: artifact_duplicate
          path: artifact
      - name: Dump2
        run: |
          mkdir artifact2
          echo $GITHUB_SHA"_latest" > artifact2/sha
      - name: Upload second
        uses: actions/upload-artifact@v4
        with:
          name: artifact_duplicate
          path: artifact2
      

